#!/usr/bin/env bash
# ============================================================
# PillSafe — Wi-Fi Access Point (Hotspot) Setup Script
# ============================================================
#
# Configures the Raspberry Pi to broadcast its own Wi-Fi network
# so the caregiver's phone can connect directly without needing
# an external Wi-Fi router.
#
# Network topology after setup:
#   Pi (192.168.4.1) ←── Wi-Fi AP "PillSafe-AP" ──→ Phone
#   Flask API accessible at http://192.168.4.1:5000
#
# Prerequisites:
#   - Raspberry Pi 4B/5 with built-in Wi-Fi (wlan0)
#   - Raspberry Pi OS Bookworm 64-bit
#   - Run as root:  sudo bash services/setup_hotspot.sh
#
# What this script does:
#   1. Installs hostapd (AP daemon) and dnsmasq (DHCP server)
#   2. Configures a static IP on wlan0
#   3. Sets up hostapd to broadcast "PillSafe-AP"
#   4. Sets up dnsmasq to hand out IP addresses to connected phones
#   5. Creates a systemd service to start the AP on boot
#
# To disable and return to normal Wi-Fi client mode:
#   sudo bash services/setup_hotspot.sh --disable
#
# ============================================================

set -euo pipefail

# ── Configuration (matches config.yaml hotspot section) ─────
SSID="PillSafe-AP"
PASSWORD="pillsafe2026"
CHANNEL=6
AP_IP="192.168.4.1"
SUBNET_MASK="255.255.255.0"
DHCP_START="192.168.4.10"
DHCP_END="192.168.4.50"
DHCP_LEASE="24h"
INTERFACE="wlan0"

# ── Colours for output ──────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[✗]${NC} $1"; }

# ── Check root ──────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
    error "This script must be run as root:  sudo bash $0"
    exit 1
fi

# ── Handle --disable flag ──────────────────────────────────
if [ "${1:-}" = "--disable" ]; then
    echo ""
    echo "=== Disabling PillSafe Wi-Fi Hotspot ==="
    echo ""

    systemctl stop hostapd 2>/dev/null || true
    systemctl stop dnsmasq 2>/dev/null || true
    systemctl disable hostapd 2>/dev/null || true
    systemctl disable dnsmasq 2>/dev/null || true

    # Restore dhcpcd config
    if [ -f /etc/dhcpcd.conf.pillsafe_backup ]; then
        cp /etc/dhcpcd.conf.pillsafe_backup /etc/dhcpcd.conf
        info "Restored original dhcpcd.conf"
    fi

    # Remove AP configs
    rm -f /etc/hostapd/hostapd.conf
    rm -f /etc/dnsmasq.d/pillsafe.conf

    # Restart networking
    systemctl restart dhcpcd 2>/dev/null || true
    systemctl restart NetworkManager 2>/dev/null || true

    info "Hotspot disabled — Pi will connect to Wi-Fi as a normal client"
    info "Reboot recommended:  sudo reboot"
    exit 0
fi

# ── Main setup ─────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  PillSafe — Wi-Fi Access Point Setup"
echo "============================================================"
echo ""
echo "  SSID:       $SSID"
echo "  Password:   $PASSWORD"
echo "  Channel:    $CHANNEL"
echo "  Pi IP:      $AP_IP"
echo "  DHCP range: $DHCP_START — $DHCP_END"
echo ""
echo "  After setup, the Flutter app connects to:"
echo "    http://$AP_IP:5000"
echo ""
echo "============================================================"
echo ""

# ── Step 1: Install packages ──────────────────────────────
info "Installing hostapd and dnsmasq..."
apt update -qq
apt install -y hostapd dnsmasq >/dev/null 2>&1

# Stop services while configuring
systemctl stop hostapd 2>/dev/null || true
systemctl stop dnsmasq 2>/dev/null || true

info "Packages installed"

# ── Step 2: Configure static IP on wlan0 ──────────────────
# Back up existing dhcpcd.conf
if [ ! -f /etc/dhcpcd.conf.pillsafe_backup ]; then
    cp /etc/dhcpcd.conf /etc/dhcpcd.conf.pillsafe_backup
    info "Backed up original dhcpcd.conf"
fi

# Check if our config block already exists
if ! grep -q "# PillSafe AP static IP" /etc/dhcpcd.conf; then
    cat >> /etc/dhcpcd.conf << EOF

# PillSafe AP static IP configuration
interface $INTERFACE
    static ip_address=$AP_IP/24
    nohook wpa_supplicant
EOF
    info "Static IP configured: $AP_IP on $INTERFACE"
else
    warn "Static IP already configured in dhcpcd.conf — skipping"
fi

# ── Step 3: Configure hostapd ─────────────────────────────
cat > /etc/hostapd/hostapd.conf << EOF
# PillSafe Wi-Fi Access Point Configuration
# Generated by setup_hotspot.sh

interface=$INTERFACE
driver=nl80211

# Network name and security
ssid=$SSID
wpa=2
wpa_passphrase=$PASSWORD
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP

# Radio settings
hw_mode=g
channel=$CHANNEL
ieee80211n=1
ieee80211d=1
country_code=GH
wmm_enabled=1

# Limits
max_num_sta=5
EOF

# Point hostapd to the config file
if [ -f /etc/default/hostapd ]; then
    sed -i 's|^#\?DAEMON_CONF=.*|DAEMON_CONF="/etc/hostapd/hostapd.conf"|' /etc/default/hostapd
fi

info "hostapd configured (SSID: $SSID, channel: $CHANNEL)"

# ── Step 4: Configure dnsmasq (DHCP server) ───────────────
cat > /etc/dnsmasq.d/pillsafe.conf << EOF
# PillSafe DHCP server configuration
# Generated by setup_hotspot.sh

interface=$INTERFACE
bind-interfaces

# DHCP range for connected devices (phones)
dhcp-range=$DHCP_START,$DHCP_END,$SUBNET_MASK,$DHCP_LEASE

# DNS — use Google DNS (for any internet pass-through)
server=8.8.8.8
server=8.8.4.4

# Helpful: resolve "pillsafe.local" to the Pi's IP
address=/pillsafe.local/$AP_IP
EOF

info "dnsmasq configured (DHCP: $DHCP_START — $DHCP_END)"

# ── Step 5: Unmask and enable services ────────────────────
systemctl unmask hostapd
systemctl enable hostapd
systemctl enable dnsmasq

info "Services enabled for boot"

# ── Step 6: Start services ────────────────────────────────
systemctl restart dhcpcd
sleep 2
systemctl start hostapd
systemctl start dnsmasq

info "hostapd and dnsmasq started"

# ── Verify ────────────────────────────────────────────────
echo ""
echo "============================================================"
echo "  Setup Complete!"
echo "============================================================"
echo ""

if systemctl is-active --quiet hostapd; then
    info "hostapd is running"
else
    error "hostapd failed to start — check: sudo journalctl -u hostapd"
fi

if systemctl is-active --quiet dnsmasq; then
    info "dnsmasq is running"
else
    error "dnsmasq failed to start — check: sudo journalctl -u dnsmasq"
fi

echo ""
echo "  Next steps:"
echo "    1. On the caregiver's phone, connect to Wi-Fi: '$SSID'"
echo "       Password: '$PASSWORD'"
echo ""
echo "    2. In the Flutter app Settings screen, set the API address to:"
echo "       http://$AP_IP:5000"
echo ""
echo "    3. To disable the hotspot and return to normal Wi-Fi:"
echo "       sudo bash services/setup_hotspot.sh --disable"
echo ""
echo "    4. A reboot is recommended:  sudo reboot"
echo ""
echo "============================================================"
